"""Generate DV360 custom-bidding scoring scripts from deevAI objectives.

Output is the DV360-proprietary DSL described in
https://support.google.com/displayvideo/answer/11967043, NOT Python.

The DSL grammar this generator targets (the only one DV360 accepts):

    # header comment lines …
    return aggregate_function([
        ([criterion, …], weight),
        ([criterion, …], weight),
        …
    ])

`sum_aggregate` is our default because we want every matching objective
to contribute additively. `first_match_aggregate` would short-circuit
on the first match and `max_aggregate` would pick the largest — both
produce non-additive behaviour that doesn't match a "weighted sliders"
mental model.

Determinism: same inputs → same script bytes. This is critical for
diff-view in the UI and for change-management ("nothing changed since
last upload, so we don't need to re-upload").
"""

from __future__ import annotations

import hashlib
import textwrap
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Final

from .objectives import (
    Criterion,
    ObjectiveId,
    Recipe,
    TenantConfig,
    expand_objectives,
)


# DV360 hard limit per their docs ("Limitations" section): scripts must
# stay under a few KB. We chose 8 KB as a conservative ceiling — well
# below any real-world DSL output for a 3-objective recipe.
MAX_SCRIPT_BYTES: Final[int] = 8 * 1024


@dataclass(frozen=True)
class GeneratedScript:
    """The artefact deevAI uploads to DV360.

    `source` is the raw DSL text. `digest_sha256` is a cheap identity
    so the UI can dedupe and the apply path can short-circuit when
    nothing changed.
    """

    source: str
    digest_sha256: str
    n_criteria: int
    aggregate_function: str
    tenant_id: str
    generated_at: datetime


def _emit_header(
    tenant_id: str,
    cfg: TenantConfig,
    generated_at: datetime,
) -> list[str]:
    """Top-of-file comment block — sufficient for an auditor to
    reconstruct intent without seeing deevAI's UI."""
    weights = cfg.weights
    return [
        "# Auto-generated by deevAI Custom Bidding Studio.",
        "# DO NOT edit by hand — changes will be overwritten on the next sync.",
        f"# Tenant: {tenant_id}",
        f"# Generated: {generated_at.isoformat()}",
        "# Sliders (weights that sum to 1.0):",
        f"#   Performance: {weights.get(ObjectiveId.PERFORMANCE, 0.0):.3f}",
        f"#   Quality:     {weights.get(ObjectiveId.QUALITY, 0.0):.3f}",
        f"#   Reach:       {weights.get(ObjectiveId.REACH, 0.0):.3f}",
    ]


def _emit_criterion(c: Criterion, scaled_weight: float, indent: str) -> list[str]:
    """Render one (criteria, weight) pair as DSL.

    Format::

        # comment (optional)
        ([criterion_expression], weight),

    `criterion_expression` is the raw DSL we stored in
    Criterion.expression. We don't re-quote or transform it — the
    validator is responsible for guarding that string.
    """
    lines: list[str] = []
    if c.comment:
        lines.append(f"{indent}# {c.comment}")
    lines.append(f"{indent}([{c.expression}], {scaled_weight:.3f}),")
    return lines


def _scale(weight_in_recipe: float, slider: float) -> float:
    """Scale a recipe's internal weight by the slider value.

    We deliberately preserve weights >0 even if the slider is tiny so
    the model still learns the *relative* ordering. If the slider is
    0, the whole objective is skipped earlier by `expand_objectives`.
    """
    return weight_in_recipe * slider


def generate_script(
    cfg: TenantConfig,
    *,
    tenant_id: str,
    aggregate: str = "sum_aggregate",
    now: datetime | None = None,
) -> GeneratedScript:
    """Generate the DV360 DSL script for the given tenant.

    Raises:
        ValueError: invalid weights, missing required Floodlight ID,
            aggregate function not allowed, or generated script over
            the size cap.
    """
    if aggregate not in {"sum_aggregate", "max_aggregate", "first_match_aggregate"}:
        raise ValueError(
            f"aggregate must be one of sum_aggregate / max_aggregate / "
            f"first_match_aggregate; got {aggregate!r}"
        )

    if now is None:
        # Wall-clock time we capture lives only in the header comment —
        # never in the logic — so callers may pin it for reproducibility.
        now = datetime.now(timezone.utc).replace(microsecond=0)

    # Expand objectives → (recipe, slider) pairs. This also validates
    # weights and required Floodlight IDs.
    expanded = expand_objectives(cfg)
    if not expanded:
        raise ValueError(
            "All objective weights are zero — no script to generate."
        )

    lines: list[str] = []
    lines.extend(_emit_header(tenant_id, cfg, now))
    lines.append("")
    lines.append(f"return {aggregate}([")

    n_criteria = 0
    indent = "    "

    for recipe, slider in expanded:
        lines.append(f"{indent}# ── {recipe.objective.value.upper()} (slider={slider:.3f}) ──")
        for c in recipe.criteria:
            scaled = _scale(c.weight, slider)
            lines.extend(_emit_criterion(c, scaled, indent))
            n_criteria += 1

    lines.append("])")

    source = "\n".join(lines) + "\n"

    if len(source.encode("utf-8")) > MAX_SCRIPT_BYTES:
        raise ValueError(
            f"Generated script is {len(source.encode())} bytes — over the "
            f"{MAX_SCRIPT_BYTES}-byte safety cap. Trim weights or objectives."
        )

    digest = hashlib.sha256(source.encode("utf-8")).hexdigest()

    return GeneratedScript(
        source=source,
        digest_sha256=digest,
        n_criteria=n_criteria,
        aggregate_function=aggregate,
        tenant_id=tenant_id,
        generated_at=now,
    )


# ─────────────────────────────────────────────────────────────── pretty-print


def render_diff(old: GeneratedScript, new: GeneratedScript) -> str:
    """Return a unified-diff-shaped string comparing two scripts.

    We don't use ``difflib`` here because the UI wants a tiny dependency
    surface. The function is intentionally minimalist: it lists which
    objective slider changed and how many criteria flipped.
    """
    if old.digest_sha256 == new.digest_sha256:
        return "(no changes)"

    parts: list[str] = []
    parts.append(f"sha {old.digest_sha256[:12]} → {new.digest_sha256[:12]}")
    parts.append(f"criteria {old.n_criteria} → {new.n_criteria}")
    parts.append(f"aggregate {old.aggregate_function} → {new.aggregate_function}")

    # naive line-level diff for the audit log
    old_lines = old.source.splitlines()
    new_lines = new.source.splitlines()
    parts.append(f"lines {len(old_lines)} → {len(new_lines)}")

    return "; ".join(parts)


def explain(script: GeneratedScript) -> str:
    """Render a multi-line human explanation of what the script does."""
    body = textwrap.dedent(
        f"""\
        deevAI Custom Bidding Script
        Tenant: {script.tenant_id}
        Generated: {script.generated_at.isoformat()}
        Aggregate: {script.aggregate_function}
        Criteria count: {script.n_criteria}
        Source bytes: {len(script.source.encode())}
        SHA256: {script.digest_sha256}
        """
    )
    return body
