"""initial schema — deevAI single-revision consolidated baseline

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-05-18

This is a fresh consolidated schema for deevAI. There is no migration
history before it. New tables ship as new revisions on top of 0001.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False, comment='active | suspended | deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('integrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('client_id', sa.String(length=160), nullable=True),
    sa.Column('client_secret_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('provider_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False, comment='pending | connected | error | disconnected'),
    sa.Column('last_health_check_at', sa.String(length=40), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_tenant_id'), 'integrations', ['tenant_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('default_cpv_target', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('tolerance_band', sa.Numeric(precision=4, scale=3), nullable=False, comment='±20% around target = on_target'),
    sa.Column('max_step_per_run', sa.Numeric(precision=4, scale=3), nullable=False, comment='Cap on modifier delta per weekly run'),
    sa.Column('max_modifier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('min_modifier_active', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('exploration_revive_after_runs', sa.Integer(), nullable=False),
    sa.Column('exploration_revive_modifier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('min_impressions_for_action', sa.Integer(), nullable=False),
    sa.Column('min_visits_for_strong_action', sa.Integer(), nullable=False),
    sa.Column('anomalous_ctr_threshold', sa.Numeric(precision=5, scale=4), nullable=False, comment='CTR above this triggers click-farm filter'),
    sa.Column('min_viewability', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('observation_only_until', sa.DateTime(timezone=True), nullable=True, comment="No live writes before this date — deevAI's 14-day promise"),
    sa.Column('default_line_item_mode', sa.String(length=32), nullable=False, comment='Mode applied to line items after observation_only_until'),
    sa.Column('digest_language', sa.String(length=8), nullable=False, comment='ISO 639-1 language code for the weekly digest'),
    sa.Column('digest_delivery_email', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_tenant_id'), 'settings', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False, comment='owner | member | viewer'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='active | invited | disabled'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('advertisers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('amazon_advertiser_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False, comment='active | paused | archived'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisers_amazon_advertiser_id'), 'advertisers', ['amazon_advertiser_id'], unique=False)
    op.create_index(op.f('ix_advertisers_integration_id'), 'advertisers', ['integration_id'], unique=False)
    op.create_index(op.f('ix_advertisers_tenant_id'), 'advertisers', ['tenant_id'], unique=False)
    op.create_table('line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('advertiser_id', sa.String(length=36), nullable=False),
    sa.Column('amazon_line_item_id', sa.String(length=80), nullable=False),
    sa.Column('amazon_ad_group_id', sa.String(length=80), nullable=True),
    sa.Column('amazon_bid_adjustment_rule_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('cpv_target', sa.Numeric(precision=10, scale=4), nullable=False, comment="Cost per visit target, in the advertiser's currency"),
    sa.Column('current_max_bid', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('visit_event_id', sa.String(length=80), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False, comment='observation_only | approval_required | auto_apply'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='active | paused | archived'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_items_advertiser_id'), 'line_items', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_line_items_amazon_ad_group_id'), 'line_items', ['amazon_ad_group_id'], unique=False)
    op.create_index(op.f('ix_line_items_amazon_line_item_id'), 'line_items', ['amazon_line_item_id'], unique=False)
    op.create_index(op.f('ix_line_items_tenant_id'), 'line_items', ['tenant_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('line_item_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False, comment='visit | lead | purchase | engagement | custom'),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('value_eur', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('value_source', sa.String(length=16), nullable=False, comment='static | dynamic | modeled'),
    sa.Column('value_currency', sa.String(length=3), nullable=False),
    sa.Column('tracking_source', sa.String(length=24), nullable=False, comment='pixel | s2s_postback | api | manual_upload'),
    sa.Column('attribution_window_hours', sa.Integer(), nullable=False),
    sa.Column('dedupe_rule', sa.String(length=20), nullable=False, comment='per_session | per_user | first_only | every'),
    sa.Column('quality_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('funnel_parent_id', sa.String(length=36), nullable=True),
    sa.Column('funnel_position', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False, comment='active | paused | archived'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['funnel_parent_id'], ['actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_funnel_parent_id'), 'actions', ['funnel_parent_id'], unique=False)
    op.create_index(op.f('ix_actions_line_item_id'), 'actions', ['line_item_id'], unique=False)
    op.create_index(op.f('ix_actions_tenant_id'), 'actions', ['tenant_id'], unique=False)
    op.create_table('agent_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False, comment='setup | tuning'),
    sa.Column('line_item_id', sa.String(length=36), nullable=True),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('proposed_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | approved | rejected | applied | reverted | failed'),
    sa.Column('auto_applicable', sa.Boolean(), nullable=False),
    sa.Column('approver_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('post_mortem_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('post_mortem', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_model', sa.String(length=60), nullable=True),
    sa.Column('llm_input_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_proposals_line_item_id'), 'agent_proposals', ['line_item_id'], unique=False)
    op.create_index(op.f('ix_agent_proposals_tenant_id'), 'agent_proposals', ['tenant_id'], unique=False)
    op.create_table('mai_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('line_item_id', sa.String(length=36), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action', sa.String(length=24), nullable=False, comment='planned | executed | dismissed'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mai_log_line_item_id'), 'mai_log', ['line_item_id'], unique=False)
    op.create_index(op.f('ix_mai_log_tenant_id'), 'mai_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_mai_log_user_id'), 'mai_log', ['user_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('line_item_id', sa.String(length=36), nullable=False),
    sa.Column('week_label', sa.String(length=60), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False, comment='running | succeeded | failed | cancelled'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('blended_cpv_target', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('blended_cpv_observed', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('blended_impressions', sa.Integer(), nullable=True),
    sa.Column('blended_clicks', sa.Integer(), nullable=True),
    sa.Column('blended_visits', sa.Integer(), nullable=True),
    sa.Column('blended_spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('blended_roas', sa.Numeric(precision=12, scale=4), nullable=True, comment='Σ(value_eur × action counts) / spend for the window'),
    sa.Column('n_decisions', sa.Integer(), nullable=False),
    sa.Column('n_changes_proposed', sa.Integer(), nullable=False),
    sa.Column('n_changes_applied', sa.Integer(), nullable=False),
    sa.Column('digest_text', sa.Text(), nullable=True),
    sa.Column('digest_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_line_item_id'), 'runs', ['line_item_id'], unique=False)
    op.create_index(op.f('ix_runs_tenant_id'), 'runs', ['tenant_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False, comment='user | setup_agent | tuning_agent | system'),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False, comment='create | update | delete | apply | revert'),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposal_id'], ['agent_proposals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('targeting_module', sa.String(length=40), nullable=False),
    sa.Column('targeting_key', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=240), nullable=False),
    sa.Column('field_label', sa.String(length=240), nullable=True),
    sa.Column('previous_modifier', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('new_modifier', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False, comment='under_target | over_target | on_target | insufficient_volume | anomalous_ctr | low_viewability | zero_visits | exploration_revive | smoothed'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('observed_impressions', sa.Integer(), nullable=True),
    sa.Column('observed_clicks', sa.Integer(), nullable=True),
    sa.Column('observed_visits', sa.Integer(), nullable=True),
    sa.Column('observed_cpv', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False, comment='proposed | approved | rejected | applied | failed_to_apply'),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_run_id'), 'decisions', ['run_id'], unique=False)
    op.create_index(op.f('ix_decisions_tenant_id'), 'decisions', ['tenant_id'], unique=False)
    op.create_table('optimization_strategies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('line_item_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False, comment='single | blended_2 | blended_3'),
    sa.Column('primary_metric', sa.String(length=40), nullable=False, comment='cpv | cpc | cpcv | cpm | cpa | roas | custom_action'),
    sa.Column('primary_target', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('primary_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('secondary_metric', sa.String(length=40), nullable=True),
    sa.Column('secondary_target', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('secondary_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tertiary_metric', sa.String(length=40), nullable=True),
    sa.Column('tertiary_target', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('tertiary_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('primary_action_id', sa.String(length=36), nullable=True),
    sa.Column('tolerance_band', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_action_id'], ['actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_strategies_line_item_id'), 'optimization_strategies', ['line_item_id'], unique=True)
    op.create_index(op.f('ix_optimization_strategies_tenant_id'), 'optimization_strategies', ['tenant_id'], unique=False)
    op.create_table('hard_constraints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('optimization_strategy_id', sa.String(length=36), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False, comment='cpc | cpm | cpcv | vtr | viewability | fraud_rate | roas | revenue_per_day | volume_per_day'),
    sa.Column('operator', sa.String(length=4), nullable=False, comment='gte | lte'),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('violation_policy', sa.String(length=16), nullable=False, comment='freeze | throttle | kill | alert'),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['optimization_strategy_id'], ['optimization_strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hard_constraints_optimization_strategy_id'), 'hard_constraints', ['optimization_strategy_id'], unique=False)
    op.create_index(op.f('ix_hard_constraints_tenant_id'), 'hard_constraints', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hard_constraints_tenant_id'), table_name='hard_constraints')
    op.drop_index(op.f('ix_hard_constraints_optimization_strategy_id'), table_name='hard_constraints')
    op.drop_table('hard_constraints')
    op.drop_index(op.f('ix_optimization_strategies_tenant_id'), table_name='optimization_strategies')
    op.drop_index(op.f('ix_optimization_strategies_line_item_id'), table_name='optimization_strategies')
    op.drop_table('optimization_strategies')
    op.drop_index(op.f('ix_decisions_tenant_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_run_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_runs_tenant_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_line_item_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_mai_log_user_id'), table_name='mai_log')
    op.drop_index(op.f('ix_mai_log_tenant_id'), table_name='mai_log')
    op.drop_index(op.f('ix_mai_log_line_item_id'), table_name='mai_log')
    op.drop_table('mai_log')
    op.drop_index(op.f('ix_agent_proposals_tenant_id'), table_name='agent_proposals')
    op.drop_index(op.f('ix_agent_proposals_line_item_id'), table_name='agent_proposals')
    op.drop_table('agent_proposals')
    op.drop_index(op.f('ix_actions_tenant_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_line_item_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_funnel_parent_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_line_items_tenant_id'), table_name='line_items')
    op.drop_index(op.f('ix_line_items_amazon_line_item_id'), table_name='line_items')
    op.drop_index(op.f('ix_line_items_amazon_ad_group_id'), table_name='line_items')
    op.drop_index(op.f('ix_line_items_advertiser_id'), table_name='line_items')
    op.drop_table('line_items')
    op.drop_index(op.f('ix_advertisers_tenant_id'), table_name='advertisers')
    op.drop_index(op.f('ix_advertisers_integration_id'), table_name='advertisers')
    op.drop_index(op.f('ix_advertisers_amazon_advertiser_id'), table_name='advertisers')
    op.drop_table('advertisers')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_settings_tenant_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_integrations_tenant_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
