"""Run — one weekly execution of the agent for a single LineItem.

The Run aggregates:
- The blended performance numbers for that week
- The set of Decisions the agent generated
- Lifecycle (running, succeeded, failed)
- A reference to the narrative digest generated by the LLM

We keep the digest as a column on Run because it's a write-once artifact
tied 1:1 to a run; no need for a separate table."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base, TenantScopedMixin, TimestampMixin, new_uuid, utcnow


class Run(Base, TimestampMixin, TenantScopedMixin):
    __tablename__ = "runs"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)

    line_item_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("line_items.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Observation window
    week_label: Mapped[str] = mapped_column(String(60), nullable=False)
    window_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    window_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # Lifecycle
    status: Mapped[str] = mapped_column(
        String(32), default="running", nullable=False,
        comment="running | succeeded | failed | cancelled",
    )
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, nullable=False,
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    error_message: Mapped[str | None] = mapped_column(Text)

    # Blended performance for the window
    blended_cpv_target: Mapped[float | None] = mapped_column(Numeric(10, 4))
    blended_cpv_observed: Mapped[float | None] = mapped_column(Numeric(10, 4))
    blended_impressions: Mapped[int | None] = mapped_column(Integer)
    blended_clicks: Mapped[int | None] = mapped_column(Integer)
    blended_visits: Mapped[int | None] = mapped_column(Integer)
    blended_spend: Mapped[float | None] = mapped_column(Numeric(12, 2))
    blended_roas: Mapped[float | None] = mapped_column(
        Numeric(12, 4),
        comment="Σ(value_eur × action counts) / spend for the window",
    )

    # Counts (denormalized for fast UI rendering)
    n_decisions: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    n_changes_proposed: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    n_changes_applied: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Reporting counters (denormalized, populated lazily by the scheduler).
    # All nullable so existing runs keep working — reporting service falls
    # back to live aggregation from `decisions` when these are NULL.
    n_terms_evaluated: Mapped[int | None] = mapped_column(Integer, nullable=True)
    n_terms_changed: Mapped[int | None] = mapped_column(Integer, nullable=True)
    n_terms_boosted: Mapped[int | None] = mapped_column(Integer, nullable=True)
    n_terms_cut: Mapped[int | None] = mapped_column(Integer, nullable=True)
    n_terms_zeroed: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Narrative digest, generated by the LLM after the run.
    digest_text: Mapped[str | None] = mapped_column(Text)
    digest_generated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    def __repr__(self) -> str:
        return f"<Run {self.id[:8]} week={self.week_label} status={self.status}>"
